name: Caller Workflow

on: workflow_dispatch

jobs:
  calling-workflow:
    uses: hung-snyk/Snyk-cicd-templates/.github/workflows/snyk-gha-cli-template.yml@main  # Specify repo and branch
    with:
      flag: "--all-projects"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
